# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
      time: '11:55'
      timezone: 'Asia/Tokyo'
    ignore:
      - dependency-name: '@types/node'
        versions: ['22.x.x', '21.x.x']
  - package-ecosystem: 'npm'
    directory: '/web/'
    schedule:
      interval: 'daily'
      time: '11:55'
      timezone: 'Asia/Tokyo'
    groups:
      storybook:
        patterns:
          - 'storybook'
          - '@storybook/*'
        exclude-patterns:
          - '@storybook/testing-library'
    ignore:
      - dependency-name: '@types/node'
        versions: ['22.x.x', '21.x.x']
  - package-ecosystem: 'npm'
    directory: '/backend/'
    schedule:
      interval: 'daily'
      time: '11:55'
      timezone: 'Asia/Tokyo'
    groups:
      opentelemetry:
        patterns:
          - '@opentelemetry/*'
      prisma:
        patterns:
          - 'prisma'
          - '@prisma/*'
