### POST /x/channels/ranking/last-24-hours
POST http://localhost:15000/api/x/channels/ranking/last-24-hours
x-api-key: {{$dotenv X_POST_KEY}}



### POST IndexNow
POST https://www.bing.com/IndexNow
content-type: application/json; charset=utf-8

{
  "host": "www.vcharts.net",
  "key": "ade1909491814510863e9169043a1160",
  "keyLocation": "https://www.vcharts.net/ade1909491814510863e9169043a1160.txt",
  "urlList": [
    "https://www.vcharts.net",
    "https://www.vcharts.net/ja",
    "https://www.vcharts.net/en",
    "https://www.vcharts.net/ja/hololive",
    "https://www.vcharts.net/en/hololive",
    "https://www.vcharts.net/ja/ranking/super-chat/channels/all/last24Hours",
    "https://www.vcharts.net/ja/ranking/super-chat/channels/all/last7Days",
    "https://www.vcharts.net/ja/ranking/super-chat/channels/all/last30Days",
    "https://www.vcharts.net/ja/ranking/super-chat/channels/all/last1Year",
    "https://www.vcharts.net/ja/ranking/super-chat/channels/all/thisWeek",
    "https://www.vcharts.net/ja/ranking/super-chat/channels/all/thisMonth",
    "https://www.vcharts.net/ja/ranking/super-chat/channels/all/thisYear",
    "https://www.vcharts.net/en/ranking/super-chat/channels/all/last24Hours",
    "https://www.vcharts.net/en/ranking/super-chat/channels/all/last7Days",
    "https://www.vcharts.net/en/ranking/super-chat/channels/all/last30Days",
    "https://www.vcharts.net/en/ranking/super-chat/channels/all/last1Year",
    "https://www.vcharts.net/en/ranking/super-chat/channels/all/thisWeek",
    "https://www.vcharts.net/en/ranking/super-chat/channels/all/thisMonth",
    "https://www.vcharts.net/en/ranking/super-chat/channels/all/thisYear"
  ]
}