/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/hP1QXIEy3Wf
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import ChannelCard from 'features/youtube/channel/ChannelCard'
import Link from 'next/link'

export function ChannelCards() {
  return (
    <section className="grid grid-cols-1 gap-4 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">
      <ChannelCard
        name="じごちゃんねる"
        src="https://yt3.ggpht.com/1lAOklxbCLAwfCLRroUAnlwHPku0TP9_yb4cK45rLrqzaIeFKXCL8wHwi2cEBjXWoOZz5GBVVw=s240-c-k-c0xffffffff-no-rj-mo"
      />
      <ChannelCard
        name="フロントライナーちゃん / FF14"
        src="https://yt3.ggpht.com/cTOkSS7yRKMpe0Kt3QHrxVLiShqJ0myM7XKUutXLRMcdvT5dXyzB0pBF686d39DINuKQeksq=s240-c-k-c0xffffffff-no-rj-mo"
      />
      <ChannelCard
        name="根暗ちゃんねる"
        src="https://yt3.ggpht.com/lmPsNv0GmtXtDb6N1oYPDQPKvXnRDIbBa1DFxd68-d40YvScEzmxYUd6VBAmkixwneU8B75RBg=s240-c-k-c0xffffffff-no-rj-mo"
      />

      <div className="relative overflow-hidden transition-transform duration-300 ease-in-out rounded-lg border shadow-md group hover:shadow-lg hover:-translate-y-2 flex items-center">
        <Link href="#" className="absolute inset-0 z-10" prefetch={false}>
          <span className="sr-only">View Channel</span>
        </Link>
        <img
          src="/placeholder.svg"
          alt="Channel Thumbnail"
          width={300}
          height={200}
          className="object-cover w-[30%] h-full rounded-l-lg"
        />
        <div className="p-4 bg-background flex-1 w-[70%]">
          <h3 className="text-lg font-bold line-clamp-1 mb-1">
            Fireship - Web Development Tutorials
          </h3>
          <div className="flex items-center gap-2 text-sm text-muted-foreground">
            <DollarSignIcon className="w-4 h-4" />
            <span>$800K</span>
          </div>
          <div className="flex items-center gap-2 text-sm text-muted-foreground">
            <UsersIcon className="w-4 h-4" />
            <span>2.1M Subscribers</span>
          </div>
        </div>
      </div>
      <div className="relative overflow-hidden transition-transform duration-300 ease-in-out rounded-lg border shadow-md group hover:shadow-lg hover:-translate-y-2 flex items-center">
        <Link href="#" className="absolute inset-0 z-10" prefetch={false}>
          <span className="sr-only">View Channel</span>
        </Link>
        <img
          src="/placeholder.svg"
          alt="Channel Thumbnail"
          width={300}
          height={200}
          className="object-cover w-[30%] h-full rounded-l-lg"
        />
        <div className="p-4 bg-background flex-1 w-[70%]">
          <h3 className="text-lg font-bold line-clamp-1 mb-1">
            Traversy Media - Web Development Tutorials
          </h3>
          <div className="flex items-center gap-2 text-sm text-muted-foreground">
            <DollarSignIcon className="w-4 h-4" />
            <span>$600K</span>
          </div>
          <div className="flex items-center gap-2 text-sm text-muted-foreground">
            <UsersIcon className="w-4 h-4" />
            <span>1.8M Subscribers</span>
          </div>
        </div>
      </div>
      <div className="relative overflow-hidden transition-transform duration-300 ease-in-out rounded-lg border shadow-md group hover:shadow-lg hover:-translate-y-2 flex items-center">
        <Link href="#" className="absolute inset-0 z-10" prefetch={false}>
          <span className="sr-only">View Channel</span>
        </Link>
        <img
          src="/placeholder.svg"
          alt="Channel Thumbnail"
          width={300}
          height={200}
          className="object-cover w-[30%] h-full rounded-l-lg"
        />
        <div className="p-4 bg-background flex-1 w-[70%]">
          <h3 className="text-lg font-bold line-clamp-1 mb-1">
            The Coding Train - Creative Coding Tutorials
          </h3>
          <div className="flex items-center gap-2 text-sm text-muted-foreground">
            <DollarSignIcon className="w-4 h-4" />
            <span>$400K</span>
          </div>
          <div className="flex items-center gap-2 text-sm text-muted-foreground">
            <UsersIcon className="w-4 h-4" />
            <span>1.2M Subscribers</span>
          </div>
        </div>
      </div>
      <div className="relative overflow-hidden transition-transform duration-300 ease-in-out rounded-lg border shadow-md group hover:shadow-lg hover:-translate-y-2 flex items-center">
        <Link href="#" className="absolute inset-0 z-10" prefetch={false}>
          <span className="sr-only">View Channel</span>
        </Link>
        <img
          src="/placeholder.svg"
          alt="Channel Thumbnail"
          width={300}
          height={200}
          className="object-cover w-[30%] h-full rounded-l-lg"
        />
        <div className="p-4 bg-background flex-1 w-[70%]">
          <h3 className="text-lg font-bold line-clamp-1 mb-1">
            Academind - Web Development Tutorials
          </h3>
          <div className="flex items-center gap-2 text-sm text-muted-foreground">
            <DollarSignIcon className="w-4 h-4" />
            <span>$350K</span>
          </div>
          <div className="flex items-center gap-2 text-sm text-muted-foreground">
            <UsersIcon className="w-4 h-4" />
            <span>1M Subscribers</span>
          </div>
        </div>
      </div>
      <div className="relative overflow-hidden transition-transform duration-300 ease-in-out rounded-lg border shadow-md group hover:shadow-lg hover:-translate-y-2 flex items-center">
        <Link href="#" className="absolute inset-0 z-10" prefetch={false}>
          <span className="sr-only">View Channel</span>
        </Link>
        <img
          src="/placeholder.svg"
          alt="Channel Thumbnail"
          width={300}
          height={200}
          className="object-cover w-[30%] h-full rounded-l-lg"
        />
        <div className="p-4 bg-background flex-1 w-[70%]">
          <h3 className="text-lg font-bold line-clamp-1 mb-1">
            Codevolution - React.js Tutorials
          </h3>
          <div className="flex items-center gap-2 text-sm text-muted-foreground">
            <DollarSignIcon className="w-4 h-4" />
            <span>$300K</span>
          </div>
          <div className="flex items-center gap-2 text-sm text-muted-foreground">
            <UsersIcon className="w-4 h-4" />
            <span>850K Subscribers</span>
          </div>
        </div>
      </div>
      <div className="relative overflow-hidden transition-transform duration-300 ease-in-out rounded-lg border shadow-md group hover:shadow-lg hover:-translate-y-2 flex items-center">
        <Link href="#" className="absolute inset-0 z-10" prefetch={false}>
          <span className="sr-only">View Channel</span>
        </Link>
        <img
          src="/placeholder.svg"
          alt="Channel Thumbnail"
          width={300}
          height={200}
          className="object-cover w-[30%] h-full rounded-l-lg"
        />
        <div className="p-4 bg-background flex-1 w-[70%]">
          <h3 className="text-lg font-bold line-clamp-1 mb-1">
            Clever Programmer - Programming Tutorials
          </h3>
          <div className="flex items-center gap-2 text-sm text-muted-foreground">
            <DollarSignIcon className="w-4 h-4" />
            <span>$280K</span>
          </div>
          <div className="flex items-center gap-2 text-sm text-muted-foreground">
            <UsersIcon className="w-4 h-4" />
            <span>780K Subscribers</span>
          </div>
        </div>
      </div>
      <div className="relative overflow-hidden transition-transform duration-300 ease-in-out rounded-lg border shadow-md group hover:shadow-lg hover:-translate-y-2 flex items-center">
        <Link href="#" className="absolute inset-0 z-10" prefetch={false}>
          <span className="sr-only">View Channel</span>
        </Link>
        <img
          src="/placeholder.svg"
          alt="Channel Thumbnail"
          width={300}
          height={200}
          className="object-cover w-[30%] h-full rounded-l-lg"
        />
        <div className="p-4 bg-background flex-1 w-[70%]">
          <h3 className="text-lg font-bold line-clamp-1 mb-1">
            Coder Coder - Web Development Tutorials
          </h3>
          <div className="flex items-center gap-2 text-sm text-muted-foreground">
            <DollarSignIcon className="w-4 h-4" />
            <span>$250K</span>
          </div>
          <div className="flex items-center gap-2 text-sm text-muted-foreground">
            <UsersIcon className="w-4 h-4" />
            <span>650K Subscribers</span>
          </div>
        </div>
      </div>
    </section>
  )
}

function DollarSignIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <line x1="12" x2="12" y1="2" y2="22" />
      <path d="M17 5H9.5a3.5 3.5 0 0 0 0 7h5a3.5 3.5 0 0 1 0 7H6" />
    </svg>
  )
}

function UsersIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2" />
      <circle cx="9" cy="7" r="4" />
      <path d="M22 21v-2a4 4 0 0 0-3-3.87" />
      <path d="M16 3.13a4 4 0 0 1 0 7.75" />
    </svg>
  )
}
