main:
  steps:
    - init:
        assign:
          - project: ${sys.get_env("GOOGLE_CLOUD_PROJECT_ID")}
          - location: ${sys.get_env("GOOGLE_CLOUD_LOCATION")}
          - jobName: ${sys.get_env("JOB_NAME")}
          - jobId: ${jobName + string(int(sys.now()))}
          - image: ${sys.get_env("IMAGE")}
    - create_job:
        call: googleapis.batch.v1.projects.locations.jobs.create
        args:
          parent: ${"projects/" + project + "/locations/" + location}
          jobId: ${jobId}
          body:
            priority: 99
            taskGroups:
              taskSpec:
                runnables:
                  script:
                    text: 'echo Hello World!'
                computeResource:
                  cpuMilli: 1000
                  memoryMib: 16
                environment:
                  variables:
                    ENV_NAME: production
              taskCount: 1
            allocationPolicy:
              instances:
                policy:
                  machineType: e2-micro
            logsPolicy:
              destination: CLOUD_LOGGING
    - delete_job:
        call: googleapis.batch.v1.projects.locations.jobs.delete
        args:
          name: ${"projects/" + project + "/locations/" + location + "/jobs/" + jobId}
