# This workflow demonstrates how to use the Batch connector.
# This workflow sends a List request to Batch connector.
main:
  steps:
    - init:
        assign:
          - project: ${sys.get_env("GOOGLE_CLOUD_PROJECT_ID")}
          - location: ${sys.get_env("GOOGLE_CLOUD_LOCATION")}
          - jobId: ${"example-" + string(int(sys.now()))}
          - image: ${sys.get_env("IMAGE")}
    - create_job:
        call: googleapis.batch.v1.projects.locations.jobs.create
        args:
          parent: ${"projects/" + project + "/locations/" + location}
          jobId: ${jobId}
          body:
            priority: 99
            taskGroups:
              taskSpec:
                runnables:
                  script:
                    text: 'echo Hello World!'
                computeResource:
                  cpuMilli: 1000
                  memoryMib: 16
              taskCount: 1
            environment:
              variables:
                ENV_NAME: production
            logsPolicy:
              destination: CLOUD_LOGGING
    - delete_job:
        call: googleapis.batch.v1.projects.locations.jobs.delete
        args:
          name: ${"projects/" + project + "/locations/" + location + "/jobs/" + jobId}
