-- Insert existing GroupStrings data into Group table
INSERT INTO "Group" (id, name, "iconSrc", "updatedAt") VALUES
  ('774inc', '774inc', '/group/774inc/logo.png', CURRENT_TIMESTAMP),
  ('atatakakunaru', 'あたたかくなる', '/group/atatakakunaru/logo.png', CURRENT_TIMESTAMP),
  ('dotlive', '.LIVE', '/group/dotlive/logo.png', CURRENT_TIMESTAMP),
  ('first-stage', 'First Stage Production', '/group/first-stage/logo.png', CURRENT_TIMESTAMP),
  ('hololive', 'ホロライブ', '/group/hololive/logo.png', CURRENT_TIMESTAMP),
  ('hololive-english', 'Hololive English', '/group/hololive-english/logo.png', CURRENT_TIMESTAMP),
  ('hololive-indonesia', 'Hololive Indonesia', '/group/hololive-indonesia/logo.png', CURRENT_TIMESTAMP),
  ('holostars', 'ホロスターズ', '/group/holostars/logo.png', CURRENT_TIMESTAMP),
  ('nijisanji', 'にじさんじ', '/group/nijisanji/logo.png', CURRENT_TIMESTAMP),
  ('nijisanji-en', 'NIJISANJI EN', '/group/nijisanji-en/logo.png', CURRENT_TIMESTAMP),
  ('noripro', 'のりプロ', '/group/noripro/logo.png', CURRENT_TIMESTAMP),
  ('vspo', 'ぶいすぽっ！', '/group/vspo/logo.png', CURRENT_TIMESTAMP),
  ('kizuna-ai', 'Kizuna AI', '/group/kizuna-ai/logo.png', CURRENT_TIMESTAMP),
  ('neo-porte', 'Neo-Porte', '/group/neo-porte/logo.png', CURRENT_TIMESTAMP),
  ('aogiri-high-school', '青鬼高校', '/group/aogiri-high-school/logo.png', CURRENT_TIMESTAMP),
  ('specialite', 'Specialite', '/group/specialite/logo.png', CURRENT_TIMESTAMP),
  ('mixstgirls', 'MixstGirls', '/group/mixstgirls/logo.png', CURRENT_TIMESTAMP),
  ('idol-corp', 'idol Corp', '/group/idol-corp/logo.png', CURRENT_TIMESTAMP),
  ('trillionstage', 'TrillionStage', '/group/trillionstage/logo.png', CURRENT_TIMESTAMP),
  ('utatane', 'うたたね', '/group/utatane/logo.png', CURRENT_TIMESTAMP),
  ('varium', 'Varium', '/group/varium/logo.png', CURRENT_TIMESTAMP),
  ('vividv', 'ViViD', '/group/vividv/logo.png', CURRENT_TIMESTAMP),
  ('voms', 'VOMS', '/group/voms/logo.png', CURRENT_TIMESTAMP),
  ('independent', '個人勢VTuber', '/group/independent/logo.png', CURRENT_TIMESTAMP),
  ('independent-irl', '個人勢IRL', '/group/independent-irl/logo.png', CURRENT_TIMESTAMP),
  ('artist', 'アーティスト', '/group/artist/logo.png', CURRENT_TIMESTAMP)
ON CONFLICT (id) DO NOTHING;