export const GroupStrings = [
  '774inc',
  'atatakakunaru',
  'dotlive',
  'first-stage',
  'hololive',
  'hololive-english',
  'hololive-indonesia',
  'holostars',
  'nijisanji',
  'nijisanji-en',
  'noripro',
  'vspo',
  'kizuna-ai',
  'neo-porte',
  'aogiri-high-school',
  'specialite',
  'mixstgirls',
  'idol-corp',
  'trillionstage',
  'utatane',
  'varium',
  'vividv',
  'voms',
  'independent',
  'independent-irl',
  'artist'
] as const

export type GroupString = (typeof GroupStrings)[number] | 'all'
