name: 'backend.deploy.batch-images'
on:
  push:
    branches:
      - develop
      - main

permissions: write-all

env:
  GCP_PROJECT_ID: ${{ vars.GCP_PROJECT_ID }}
  GCP_REGION: ${{ vars.GCP_REGION }}

jobs:
  backend-deploy-batch-images:
    strategy:
      matrix:
        service_name: [update-chats]
    uses: ./.github/workflows/backend.reusable.docker.workflows.yml
    with:
      service_name: ${{ matrix.service_name }}
      image: ${GCP_REGION}-docker.pkg.dev/${GCP_PROJECT_ID}/cloud-run-jobs/noxi/apps/${{ matrix.service_name }}
    secrets: inherit
