name: 'backend.deploy.batch-images'
on:
  push:
    branches:
      - main

permissions: write-all

jobs:
  backend-deploy-batch-images:
    strategy:
      matrix:
        service_name: [update-chats, update-streams]
    uses: ./.github/workflows/backend.reusable.docker.workflows.yml
    with:
      service_name: ${{ matrix.service_name }}
    secrets: inherit
