name: 'backend build'
on:
  pull_request:
    branches:
      - develop
      - main

permissions: write-all

defaults:
  run:
    working-directory: backend

jobs:
  paths-filter:
    runs-on: ubuntu-latest
    outputs:
      has-changes: ${{ steps.changes.outputs.has-changes }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            has-changes:
              - backend/**

  type-check-and-build-closed-api-server:
    runs-on: ubuntu-latest
    needs: paths-filter
    if: ${{ needs.paths-filter.outputs.has-changes == 'true' }}
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
      - run: npm i
      - run: npm run lint
      - run: npm run type-check
      - run: npm run build

  build-cloud-run-jobs:
    strategy:
      matrix:
        service_name: [hololive/update-channels, pubsubhubbub, update-streams]
    runs-on: ubuntu-latest
    needs: [paths-filter]
    if: ${{ needs.paths-filter.outputs.has-changes == 'true' }}
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
      - run: npm i
      - name: Build ${{ matrix.service_name }}
        run: npm run app -- ${{ matrix.service_name }} build
