name: 'backend.deploy.batch-images'
on:
  push:
    branches:
      - develop
      - main

permissions: write-all

env:
  GCP_PROJECT_ID: ${{ vars.GCP_PROJECT_ID }}
  GCP_REGION: ${{ vars.GCP_REGION }}
  SERVICE_ACCOUNT_NAME: ${{ vars.SERVICE_ACCOUNT_NAME }}

jobs:
  paths-filter:
    runs-on: ubuntu-latest
    outputs:
      has-changes: ${{ steps.changes.outputs.has-changes }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            has-changes:
              - .github/workflows/backend.deploy.batch-images.workflows.yml
              - backend/**

  backend-deploy-batch-images:
    strategy:
      matrix:
        service_name: [update-chats]
    env:
      IMAGE: ${GCP_REGION}-docker.pkg.dev/${GCP_PROJECT_ID}/cloud-run-jobs/noxi/apps/${{ matrix.service_name }}
    runs-on: ubuntu-latest
    needs: paths-filter
    if: ${{ needs.paths-filter.outputs.has-changes == 'true' }}
    steps:
      - name: Call Docker Build and Push Workflow
        uses: ./.github/workflows/backend.reusable.docker.workflows.yml
        with:
          service_name: ${{ matrix.service_name }}
          image: ${{ env.IMAGE }}
        secrets: inherit
