name: 'backend.deploy.jobs'
on:
  push:
    branches:
      - main

permissions: write-all

jobs:
  backend-deploy-jobs-images:
    strategy:
      matrix:
        service_name: [bundle-chats, groups/update-channels, pubsubhubbub]
    uses: ./.github/workflows/backend.reusable.docker.workflows.yml
    with:
      service_name: ${{ matrix.service_name }}
      should_deploy_to_cloud_run_jobs: true
    secrets: inherit
