name: 'backend.deploy.batch-images'
on:
  push:
    branches:
      - main

permissions: write-all

env:
  GCP_PROJECT_ID: ${{ vars.GCP_PROJECT_ID }}
  GCP_REGION: ${{ vars.GCP_REGION }}
  SERVICE_ACCOUNT_NAME: ${{ vars.SERVICE_ACCOUNT_NAME }}

jobs:
  paths-filter:
    runs-on: ubuntu-latest
    outputs:
      has-changes: ${{ steps.changes.outputs.has-changes }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            has-changes:
              - .github/workflows/backend.deploy.batch-images.workflows.yml
              - backend/**

  backend-deploy-batch-images:
    strategy:
      matrix:
        service_name: [update-chats]
    env:
      IMAGE: ${GCP_REGION}-docker.pkg.dev/${GCP_PROJECT_ID}/cloud-run-jobs/noxi/apps/${{ matrix.service_name }}
    runs-on: ubuntu-latest
    needs: paths-filter
    if: ${{ needs.paths-filter.outputs.has-changes == 'true' }}
    steps:
      - uses: actions/checkout@v4

      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_JOBS_SA_KEY }}'

      - name: Configure docker to use the gcloud cli
        run: gcloud auth configure-docker ${{ env.GCP_REGION }}-docker.pkg.dev --quiet

      - name: Build a docker image
        run: |
          docker build -t ${{ env.IMAGE }} \
            --build-arg BUILD_CMD="npm run app -- ${{ matrix.service_name }} build" \
            --build-arg START_CMD="npm run app -- ${{ matrix.service_name }} prod" \
            -f backend/apps/Dockerfile.cloudrun.jobs \
            backend

      - name: Push the docker image
        run: docker push ${{ env.IMAGE }}
