name: 'backend.deploy.jobs'
on:
  push:
    branches:
      - develop # TODO: remove me
      - main

permissions: write-all

env:
  GCP_PROJECT_ID: ${{ vars.GCP_PROJECT_ID }}
  GCP_REGION: ${{ vars.GCP_REGION }}
  SERVICE_ACCOUNT_NAME: ${{ vars.SERVICE_ACCOUNT_NAME }}

jobs:
  backend-deploy-jobs-images:
    strategy:
      matrix:
        service_name: [groups/update-channels, pubsubhubbub, update-streams]
    uses: ./.github/workflows/backend.reusable.docker.workflows.yml
    with:
      service_name: ${{ matrix.service_name }}
      should_deploy_to_cloud_run_jobs: true
    secrets: inherit
