name: 'backend build'
on:
  pull_request:
    branches:
      - develop
      - main

permissions: write-all

jobs:
  paths-filter:
    runs-on: ubuntu-latest
    outputs:
      has-changes: ${{ steps.changes.outputs.has-changes }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            has-changes:
              - backend/**

  backend-build:
    runs-on: ubuntu-latest
    needs: paths-filter
    if: ${{ needs.paths-filter.outputs.has-changes == 'true' }}
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
      - run: npm ci
        working-directory: backend
      - run: npm run lint
        working-directory: backend
      - run: npm run type-check
        working-directory: backend

      - name: Build closed-api-server
        run: npm run build
        working-directory: backend
      - name: Build pubsubhubbub
        run: npm run app -- pubsubhubbub build
        working-directory: backend
