name: 'backend.deploy.jobs'
on:
  push:
    branches:
      - main

permissions: write-all

jobs:
  backend-deploy-jobs-images:
    strategy:
      matrix:
        service_name:
          [
            bundle-chats,
            bundle-chat-events,
            groups/update-channels,
            pubsubhubbub,
            summarize-channels,
            update-exchange-rates
          ]
    uses: ./.github/workflows/backend.reusable.docker.workflows.yml
    with:
      service_name: ${{ matrix.service_name }}
      should_deploy_to_cloud_run_jobs: true
    secrets: inherit
