name: 'backend.deploy.batch-images'
on:
  push:
    branches:
      - develop # TODO: remove me
      - main

permissions: write-all

env:
  GCP_PROJECT_ID: ${{ vars.GCP_PROJECT_ID }}
  GCP_REGION: ${{ vars.GCP_REGION }}

jobs:
  backend-deploy-batch-images:
    strategy:
      matrix:
        # testing: tobe update-chats
        service_name: [pubsubhubbub]
    uses: ./.github/workflows/backend.reusable.docker.workflows.yml
    with:
      service_name: ${{ matrix.service_name }}
    secrets: inherit
