name: 'web build'
on:
  pull_request:
    branches:
      - develop
      - main

permissions: write-all

defaults:
  run:
    working-directory: web

jobs:
  paths-filter:
    runs-on: ubuntu-latest
    outputs:
      has-changes: ${{ steps.changes.outputs.has-changes }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            has-changes:
              - web/**

  web-build:
    runs-on: ubuntu-latest
    needs: paths-filter
    if: ${{ needs.paths-filter.outputs.has-changes == 'true' }}
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
      - run: npm i --legacy-peer-deps
      - run: npm run lint
      - run: npm run type-check
      - name: Build web
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
        run: npm run build
